#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMvcApplication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DemoMvcData")]
	public partial class DemoMvcDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DemoMvcDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DemoMvcDataConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemoMvcDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoMvcDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoMvcDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoMvcDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StatePedCycleCrash> StatePedCycleCrashes
		{
			get
			{
				return this.GetTable<StatePedCycleCrash>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatePedCycleCrashes")]
	public partial class StatePedCycleCrash
	{
		
		private string _MAP;
		
		private string _IMAGE_NO;
		
		private string _CRASH_RPT_NO;
		
		private string _DAY_OF_WEEK;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<System.TimeSpan> _TIME;
		
		private System.Nullable<int> _VEHICLES_COUNT;
		
		private System.Nullable<int> _VEHICLE_NO;
		
		private string _PERSON_INVOLVEMENT;
		
		private string _AGENCY;
		
		private string _TROOP;
		
		private string _COUNTY;
		
		private string _CITY;
		
		private string _CRASH_TYPE;
		
		private string _SEVERITY;
		
		private string _AT_STREET;
		
		private string _ON_STREET;
		
		private string _LIGHT_CONDITIONS;
		
		private System.Nullable<int> _INJURED;
		
		private System.Nullable<int> _KILLED;
		
		private string _VEHICLE_TYPE;
		
		private string _CIRCUMSTANCES;
		
		public StatePedCycleCrash()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAP", DbType="NVarChar(15)")]
		public string MAP
		{
			get
			{
				return this._MAP;
			}
			set
			{
				if ((this._MAP != value))
				{
					this._MAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_NO", DbType="NVarChar(15)")]
		public string IMAGE_NO
		{
			get
			{
				return this._IMAGE_NO;
			}
			set
			{
				if ((this._IMAGE_NO != value))
				{
					this._IMAGE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRASH_RPT_NO", DbType="NVarChar(20)")]
		public string CRASH_RPT_NO
		{
			get
			{
				return this._CRASH_RPT_NO;
			}
			set
			{
				if ((this._CRASH_RPT_NO != value))
				{
					this._CRASH_RPT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAY_OF_WEEK", DbType="NVarChar(5)")]
		public string DAY_OF_WEEK
		{
			get
			{
				return this._DAY_OF_WEEK;
			}
			set
			{
				if ((this._DAY_OF_WEEK != value))
				{
					this._DAY_OF_WEEK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="Time")]
		public System.Nullable<System.TimeSpan> TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this._TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHICLES_COUNT", DbType="Int")]
		public System.Nullable<int> VEHICLES_COUNT
		{
			get
			{
				return this._VEHICLES_COUNT;
			}
			set
			{
				if ((this._VEHICLES_COUNT != value))
				{
					this._VEHICLES_COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHICLE_NO", DbType="Int")]
		public System.Nullable<int> VEHICLE_NO
		{
			get
			{
				return this._VEHICLE_NO;
			}
			set
			{
				if ((this._VEHICLE_NO != value))
				{
					this._VEHICLE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSON_INVOLVEMENT", DbType="NVarChar(10)")]
		public string PERSON_INVOLVEMENT
		{
			get
			{
				return this._PERSON_INVOLVEMENT;
			}
			set
			{
				if ((this._PERSON_INVOLVEMENT != value))
				{
					this._PERSON_INVOLVEMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENCY", DbType="NVarChar(50)")]
		public string AGENCY
		{
			get
			{
				return this._AGENCY;
			}
			set
			{
				if ((this._AGENCY != value))
				{
					this._AGENCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TROOP", DbType="NVarChar(3)")]
		public string TROOP
		{
			get
			{
				return this._TROOP;
			}
			set
			{
				if ((this._TROOP != value))
				{
					this._TROOP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTY", DbType="NVarChar(20)")]
		public string COUNTY
		{
			get
			{
				return this._COUNTY;
			}
			set
			{
				if ((this._COUNTY != value))
				{
					this._COUNTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(30)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRASH_TYPE", DbType="NVarChar(25)")]
		public string CRASH_TYPE
		{
			get
			{
				return this._CRASH_TYPE;
			}
			set
			{
				if ((this._CRASH_TYPE != value))
				{
					this._CRASH_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEVERITY", DbType="NVarChar(30)")]
		public string SEVERITY
		{
			get
			{
				return this._SEVERITY;
			}
			set
			{
				if ((this._SEVERITY != value))
				{
					this._SEVERITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AT_STREET", DbType="NVarChar(50)")]
		public string AT_STREET
		{
			get
			{
				return this._AT_STREET;
			}
			set
			{
				if ((this._AT_STREET != value))
				{
					this._AT_STREET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ON_STREET", DbType="NVarChar(50)")]
		public string ON_STREET
		{
			get
			{
				return this._ON_STREET;
			}
			set
			{
				if ((this._ON_STREET != value))
				{
					this._ON_STREET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGHT_CONDITIONS", DbType="NVarChar(25)")]
		public string LIGHT_CONDITIONS
		{
			get
			{
				return this._LIGHT_CONDITIONS;
			}
			set
			{
				if ((this._LIGHT_CONDITIONS != value))
				{
					this._LIGHT_CONDITIONS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INJURED", DbType="Int")]
		public System.Nullable<int> INJURED
		{
			get
			{
				return this._INJURED;
			}
			set
			{
				if ((this._INJURED != value))
				{
					this._INJURED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KILLED", DbType="Int")]
		public System.Nullable<int> KILLED
		{
			get
			{
				return this._KILLED;
			}
			set
			{
				if ((this._KILLED != value))
				{
					this._KILLED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHICLE_TYPE", DbType="NVarChar(10)")]
		public string VEHICLE_TYPE
		{
			get
			{
				return this._VEHICLE_TYPE;
			}
			set
			{
				if ((this._VEHICLE_TYPE != value))
				{
					this._VEHICLE_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIRCUMSTANCES", DbType="NVarChar(10)")]
		public string CIRCUMSTANCES
		{
			get
			{
				return this._CIRCUMSTANCES;
			}
			set
			{
				if ((this._CIRCUMSTANCES != value))
				{
					this._CIRCUMSTANCES = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
